//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn4.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class BaiViet
    {
        public int MaBaiViet { get; set; }
        public int MaChuyenMuc { get; set; }
        public int MaNhomSanPham { get; set; }
        public Nullable<int> MaKhachHang { get; set; }
        public int MaVungMien { get; set; }
        public string TieuDe { get; set; }
        public string NoiDung { get; set; }
        public Nullable<System.DateTime> NgayDang { get; set; }
        [Display(Name = "Ngày hết hạn")]
        //[Required(ErrorMessage = "Bạn chưa nhập ngày hết hạn")]
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> NgayHetHan { get; set; }
        [Display(Name = "Ngày duyệt")]
        //[Required(ErrorMessage = "Bạn chưa nhập ngày duyệt")]
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> NgayDuyet { get; set; }
        public string TenNguoiLienHe { get; set; }
        public string DiaChiLienHe { get; set; }
        public string SDTLienHe { get; set; }
        public string EmailLienHe { get; set; }
        public string Image { get; set; }
        public Nullable<double> GiaBan { get; set; }
        [Display(Name = "Trạng thái")]
        //[Required(ErrorMessage = "Bạn chưa nhập trạng thái")]
        public string TrangThai { get; set; }
    
        public virtual ChuyenMuc ChuyenMuc { get; set; }
        public virtual KhachHang KhachHang { get; set; }
        public virtual NhomSanPham NhomSanPham { get; set; }
        public virtual VungMien VungMien { get; set; }
    }
}
