//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn4.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class KhachHang
    {
        public KhachHang()
        {
            this.BaiViets = new HashSet<BaiViet>();
            this.HoaDonDangTins = new HashSet<HoaDonDangTin>();
            this.HoaDonNapTiens = new HashSet<HoaDonNapTien>();
        }

        [Display(Name = "Mã")]
        public int MaKhachHang { get; set; }
        [Display(Name = "Họ tên")]
        [Required(ErrorMessage = "Họ tên không được để trống")]
        public string HoTen { get; set; }
        [Display(Name = "Tên đăng nhập")]
        [Required(ErrorMessage = "Tên đăng nhập không được để trống")]
        [StringLength(50, ErrorMessage = "Tên không quá 50 ký tự")]
        public string TenDangNhap { get; set; }
        [Display(Name = "Mật khẩu")]
        [DataType(DataType.Password)]
        [Required(ErrorMessage = "Mật khẩu không được để trống")]
        public string MatKhau { get; set; }
        [Display(Name = "Địa Chỉ")]
        [Required(ErrorMessage = "Địa chỉ không được để trống")]
        public string DiaChi { get; set; }
        [Display(Name = "SĐT")]
        [DataType(DataType.PhoneNumber)]
        [Required(ErrorMessage = "SĐT không được để trống")]
        public string SDT { get; set; }
        [Display(Name = "Email")]
        [DataType(DataType.EmailAddress)]
        [Required(ErrorMessage = "Email không được để trống")]
        public string Email { get; set; }
        [Display(Name = "Ngày đăng ký")]
        [Required(ErrorMessage = "Ngày đăng ký không được để trống")]
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> NgayDangKi { get; set; }
        [Display(Name = "Số tiền nạp")]
        [Required(ErrorMessage = "Số tiền nạp không được để trống")]
        public Nullable<double> SoTienDaNap { get; set; }
        [Display(Name = "Ghi Chú")]
        [Required(ErrorMessage = "Ghi chú không được để trống")]
        public string GhiChu { get; set; }
    
        public virtual ICollection<BaiViet> BaiViets { get; set; }
        public virtual ICollection<HoaDonDangTin> HoaDonDangTins { get; set; }
        public virtual ICollection<HoaDonNapTien> HoaDonNapTiens { get; set; }
    }
}
