//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn4.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class NhanVien
    {
        [Display(Name = "Mã NV")]
        public int MaNhanVien { get; set; }
        [Display(Name = "Họ tên")]
        [Required(ErrorMessage = "Họ tên không được để trống")]
        public string HoTen { get; set; }
        [Display(Name = "Tên đăng nhập")]
        [Required(ErrorMessage = "Tên đăng nhập không được để trống")]
        [StringLength(50, ErrorMessage = "Tên đăng nhập không được phép quá 50 ký tự")]
        public string TenDangNhap { get; set; }
        [Display(Name = "Mật khẩu")]
        [Required(ErrorMessage = "Mật khẩu không được để trống")]
        [DataType(DataType.Password)]
        public string MatKhau { get; set; }
        [Display(Name = "SĐT")]
        [Required(ErrorMessage = "SDT không được để trống")]
        [DataType(DataType.PhoneNumber)]
        public string SDT { get; set; }
        [Display(Name = "Email")]
        [Required(ErrorMessage = "Email không được để trống")]
        [DataType(DataType.EmailAddress)]
        public string Email { get; set; }
        [Display(Name = "Image")]
        [DataType(DataType.Upload)]
        public string Image { get; set; }
        [Display(Name = "Trạng Thái")]
        [Required(ErrorMessage = "Trạng thái không được để trống")]
        public string TrangThai { get; set; }
        [Display(Name = "Quyền Hạn")]
        [Required(ErrorMessage = "Quyền hạn không được để trống")]
        public string QuyenHan { get; set; }
        [Display(Name = "Ghi Chú")]
        [Required(ErrorMessage = "Ghi Chú không được để trống")]
        public string GhiChu { get; set; }
    }
}
