//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn4.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class NhomSanPham
    {
        public NhomSanPham()
        {
            this.BaiViets = new HashSet<BaiViet>();
        }

        [Display(Name = "Mã Nhóm Sản Phẩm")]
        public int MaNhomSanPham { get; set; }
        [Display(Name = "Tên nhóm sản phẩm")]
        [Required(ErrorMessage = "Tên nhóm sản phẩm không được để trống")]
        public string TenNhomSanPham { get; set; }
        [Display(Name = "Hình Ảnh")]
        public string Image { get; set; }
        [Display(Name = "Mô Tả")]
        [Required(ErrorMessage = "Mô tả không được để trống")]
        public string MoTa { get; set; }
    
        public virtual ICollection<BaiViet> BaiViets { get; set; }
    }
}
