//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn4.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class VungMien
    {
        public VungMien()
        {
            this.BaiViets = new HashSet<BaiViet>();
        }

        [Display(Name = "Mã Vùng Miền")]
        public int MaVungMien { get; set; }
        [Display(Name = "Tên Vùng Miền")]
        [Required(ErrorMessage = "Tên vùng miền không được để trống")]
        public string TenVungMien { get; set; }
    
        public virtual ICollection<BaiViet> BaiViets { get; set; }
    }
}
